Update build release apk

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -29,12 +29,24 @@ jobs:
       - name: Decode release keystore
         run: echo "$KEYSTORE_BASE64" | base64 --decode > my-release-key.jks
 
+      - name: Make gradlew executable
+        run: chmod +x ./gradlew
+
       - name: Build Release APK
         run: ./gradlew assembleRelease \
           -Pandroid.injected.signing.store.file=my-release-key.jks \
           -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
           -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
           -Pandroid.injected.signing.key.password=$KEY_PASSWORD
+
+      - name: Verify APK exists
+        run: |
+          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
+            echo "APK built successfully."
+          else
+            echo "APK not found! Build failed." 
+            exit 1
+          fi
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
